// frontend/src/layouts/AppLayout.vue
<script setup lang="ts">
import { computed } from 'vue'
import { RouterView, useRoute, useRouter } from 'vue-router'
import {
  ApartmentOutlined,
  ApiOutlined,
  AppstoreOutlined,
  DashboardOutlined,
  FileTextOutlined,
  KeyOutlined,
  SettingOutlined,
} from '@ant-design/icons-vue'

import { menuItems } from '@/router'

const route = useRoute()
const router = useRouter()

const iconMap = {
  DashboardOutlined,
  ApartmentOutlined,
  AppstoreOutlined,
  ApiOutlined,
  KeyOutlined,
  FileTextOutlined,
  SettingOutlined,
} as const

const selectedKeys = computed<string[]>(() => {
  const match = menuItems.find((item) =>
    item.path === '/' ? route.path === '/' : route.path.startsWith(item.path),
  )
  return match ? [match.key] : []
})

const title = computed(() => {
  const matched = [...route.matched].reverse().find((m) => m.meta?.title)
  return (matched?.meta?.title as string | undefined) ?? ''
})

function onMenuClick({ key }: { key: string }) {
  const item = menuItems.find((m) => m.key === key)
  if (item) router.push(item.path)
}
</script>

<template>
  <a-layout class="app-layout">
    <a-layout-sider collapsible breakpoint="lg" theme="dark">
      <div class="brand">网管接口模拟</div>
      <a-menu
        theme="dark"
        mode="inline"
        :selected-keys="selectedKeys"
        @click="onMenuClick"
      >
        <a-menu-item v-for="item in menuItems" :key="item.key">
          <template #icon>
            <component :is="iconMap[item.icon]" />
          </template>
          <span>{{ item.label }}</span>
        </a-menu-item>
      </a-menu>
    </a-layout-sider>

    <a-layout>
      <a-layout-header class="app-header">
        <span class="page-title">{{ title }}</span>
      </a-layout-header>
      <a-layout-content class="app-content">
        <RouterView />
      </a-layout-content>
    </a-layout>
  </a-layout>
</template>

<style scoped>
.app-layout {
  min-height: 100vh;
}

.brand {
  height: 48px;
  line-height: 48px;
  color: #fff;
  font-weight: 600;
  text-align: center;
  letter-spacing: 2px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.08);
}

.app-header {
  background: #fff;
  padding: 0 24px;
  border-bottom: 1px solid #f0f0f0;
}

.page-title {
  font-size: 16px;
  font-weight: 500;
}

.app-content {
  padding: 16px 24px;
  background: #f5f5f5;
}
</style>

// frontend/src/components/AppLayout/index.tsx
import { useState } from 'react';
import { Outlet, useNavigate, useLocation } from 'react-router-dom';
import { Layout, Menu, Typography } from 'antd';
import {
  DashboardOutlined,
  ApartmentOutlined,
  ApiOutlined,
  WifiOutlined,
  FolderOutlined,
  CloudServerOutlined,
  DatabaseOutlined,
  FileTextOutlined,
  SettingOutlined,
} from '@ant-design/icons';

const { Header, Sider, Content } = Layout;

const menuItems = [
  { key: '/dashboard', icon: <DashboardOutlined />, label: '仪表盘' },
  { key: '/topology', icon: <ApartmentOutlined />, label: '拓扑编辑器' },
  { key: '/api-config', icon: <ApiOutlined />, label: 'HTTP 接口配置' },
  { key: '/snmp-config', icon: <WifiOutlined />, label: 'SNMP 配置' },
  { key: '/sftp-config', icon: <FolderOutlined />, label: 'SFTP 配置' },
  { key: '/kafka-config', icon: <CloudServerOutlined />, label: 'Kafka 配置' },
  { key: '/data', icon: <DatabaseOutlined />, label: '数据查看' },
  { key: '/logs', icon: <FileTextOutlined />, label: '日志查看' },
  { key: '/settings', icon: <SettingOutlined />, label: '系统设置' },
];

const AppLayout = () => {
  const [collapsed, setCollapsed] = useState(false);
  const navigate = useNavigate();
  const location = useLocation();

  return (
    <Layout style={{ minHeight: '100vh' }}>
      <Sider
        collapsible
        collapsed={collapsed}
        onCollapse={setCollapsed}
        theme="dark"
      >
        <div style={{ height: 32, margin: 16, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <Typography.Text strong style={{ color: '#fff', fontSize: collapsed ? 14 : 16, whiteSpace: 'nowrap' }}>
            {collapsed ? 'NMS' : 'NMS Simulator'}
          </Typography.Text>
        </div>
        <Menu
          theme="dark"
          mode="inline"
          selectedKeys={[location.pathname]}
          items={menuItems}
          onClick={({ key }) => navigate(key)}
        />
      </Sider>
      <Layout>
        <Header style={{ padding: '0 24px', background: '#fff', display: 'flex', alignItems: 'center' }}>
          <Typography.Title level={4} style={{ margin: 0 }}>
            网管系统模拟工具
          </Typography.Title>
        </Header>
        <Content style={{ margin: 24, padding: 24, background: '#fff', borderRadius: 8, minHeight: 280 }}>
          <Outlet />
        </Content>
      </Layout>
    </Layout>
  );
};

export default AppLayout;
